"""Add department and access_role to documents

Revision ID: 1c87b11d2797
Revises: b7813c6fcfc4
Create Date: 2025-09-14 16:25:29.703111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c87b11d2797'
down_revision: Union[str, Sequence[str], None] = 'b7813c6fcfc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('department', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('access_role', sa.String(), nullable=True))
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'uploaded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'access_role')
    op.drop_column('documents', 'department')
    # ### end Alembic commands ###
